# Generated by Django 4.1.6 on 2023-02-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file_path',
        ),
    ]
